CREATE TABLE RETRIES
(
  RETRY_TYPE          VARCHAR(50)              NOT NULL,
  NATURAL_IDENTIFIER  VARCHAR(513)              NOT NULL,
  RETRY_VER           INTEGER                   NOT NULL,
  PAYLOAD_DATA        BLOB                      NOT NULL,
  CREATE_TS           TIMESTAMP      DEFAULT CURRENT_TIMESTAMP           NOT NULL,
  LAST_UPDATE_TS      TIMESTAMP
)

