
CREATE TABLE RETRIES
(
  RETRY_TYPE          VARCHAR2(50)              NOT NULL,
  NATURAL_IDENTIFIER  VARCHAR2(513)              NOT NULL,
  RETRY_VER           INTEGER                   NOT NULL,
  PAYLOAD_DATA        BLOB                      NOT NULL,
  CREATE_TS           TIMESTAMP(6)              DEFAULT SYSTIMESTAMP          NOT NULL,
  LAST_UPDATE_TS      TIMESTAMP(6)
)
LOB (PAYLOAD_DATA) STORE AS SECUREFILE (
  ENABLE       STORAGE IN ROW
  RETENTION NONE )
TABLESPACE RETRY_DATA_TBS
MONITORING
/


CREATE TABLE RETRIES_ARCHIVE
(
  RETRY_TYPE          VARCHAR2(50)              NOT NULL,
  NATURAL_IDENTIFIER  VARCHAR2(513)              NOT NULL,
  RETRY_VER           INTEGER                   NOT NULL,
  PAYLOAD_DATA        BLOB                      NOT NULL,
  CREATE_TS           TIMESTAMP(6)              DEFAULT SYSTIMESTAMP          NOT NULL,
  LAST_UPDATE_TS      TIMESTAMP(6),
  ORIGINAL_TS TIMESTAMP (6) NOT NULL
)
LOB (PAYLOAD_DATA) STORE AS SECUREFILE (
  ENABLE       STORAGE IN ROW
  RETENTION NONE )
TABLESPACE RETRY_DATA_TBS
MONITORING
/