
CREATE TABLE RETRIES
(
  RETRY_TYPE          VARCHAR2(50)              NOT NULL,
  NATURAL_IDENTIFIER  VARCHAR2(513)              NOT NULL,
  RETRY_VER           INTEGER                   NOT NULL,
  PAYLOAD_DATA        BLOB                      NOT NULL,
  CREATE_TS           TIMESTAMP(6)              DEFAULT SYSTIMESTAMP          NOT NULL,
  LAST_UPDATE_TS      TIMESTAMP(6)
)
LOB (PAYLOAD_DATA) STORE AS SECUREFILE (
  ENABLE       STORAGE IN ROW
  RETENTION NONE )
TABLESPACE RETRY_DATA_TBS
MONITORING
/


CREATE UNIQUE INDEX RETRY_PK ON RETRIES
(RETRY_TYPE, NATURAL_IDENTIFIER)
TABLESPACE RETRY_INDX_TBS;

ALTER TABLE RETRIES ADD (
  CONSTRAINT RETRY_TYPE_CK
  CHECK (RETRY_TYPE = upper(RETRY_TYPE))
  ENABLE VALIDATE);

ALTER TABLE RETRIES ADD (
  CONSTRAINT RETRY_PK
  PRIMARY KEY
  (RETRY_TYPE, NATURAL_IDENTIFIER)
  USING INDEX RETRY_PK
  ENABLE VALIDATE)
/
  
CREATE TABLE RETRIES_ARCHIVE
(
  RETRY_TYPE          VARCHAR2(50)              NOT NULL,
  NATURAL_IDENTIFIER  VARCHAR2(513)              NOT NULL,
  RETRY_VER           INTEGER                   NOT NULL,
  PAYLOAD_DATA        BLOB                      NOT NULL,
  CREATE_TS           TIMESTAMP(6)              DEFAULT SYSTIMESTAMP          NOT NULL,
  LAST_UPDATE_TS      TIMESTAMP(6),
  ORIGINAL_TS TIMESTAMP (6) NOT NULL
)
LOB (PAYLOAD_DATA) STORE AS SECUREFILE (
  ENABLE       STORAGE IN ROW
  RETENTION NONE )
TABLESPACE RETRY_DATA_TBS
MONITORING
/

CREATE INDEX RETRIES_ARCHIVE_IDX ON RETRIES_ARCHIVE
(RETRY_TYPE, NATURAL_IDENTIFIER, RETRY_VER, ORIGINAL_TS)
TABLESPACE RETRY_INDX_TBS
/

ALTER TABLE RETRIES_ARCHIVE ADD (
  CONSTRAINT RETRIES_ARCHIVE_TYPE_CK
  CHECK (RETRY_TYPE = upper(RETRY_TYPE))
  ENABLE VALIDATE);
  
/

