package ies.retry.spi.hazelcast.remote;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hazelcast.client.ClientConfig;
import com.hazelcast.client.HazelcastClient;
import com.hazelcast.config.GroupConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.Member;

import ies.retry.ConfigException;
import ies.retry.NoCallbackException;
import ies.retry.Retry;
import ies.retry.RetryCallback;
import ies.retry.RetryConfigManager;
import ies.retry.RetryConfiguration;
import ies.retry.RetryHolder;
import ies.retry.RetryManager;
import ies.retry.RetryState;
import ies.retry.RetryTransitionListener;
import ies.retry.spi.hazelcast.HzSerializableRetryHolder;
import ies.retry.spi.hazelcast.remote.RemoteCallback.DefaultRemoteCallback;
import ies.retry.spi.hazelcast.util.KryoSerializer;


/**
 * This instance of Retrymanager exists purely as a client reference to the cluster.
 * 
 * For the purposes of callback, 
 * 
 * @author msimonsen
 *
 */
public class RetryRemoteManagerImpl extends Remoteable implements RetryManager {

	/**
	 * client to the target cluster
	 */
	
	HazelcastInstance cluster = null;
	
	private Map<String,RetryCallback> localCallbackMap = new HashMap<String, RetryCallback>();
	
	
		
	RemoteConfigManager configManager = null;

	/**
	 * Discovers client configuration information through 
	 * retry configuration. 
	 */
	public RetryRemoteManagerImpl() {
		
				
		this.configManager = new RemoteConfigManager();
		
		
		HazelcastClient client = HazelcastClient.newHazelcastClient(((RemoteXmlConfig)configManager.getConfig()).getHzClientConfig());
		
		this.hzClient = client;
		configManager.setHzInstance(hzClient);
		
		addConfigurations();
	}

	
	/**
	 * Reference the callback cluster by name
	 * @param clientInstance - the client to the retry server
	 * @param clusterName - the callback cluster (this cluster)
	 */
	protected void init(HazelcastClient clientInstance,String clusterName) {
		
		hzClient = clientInstance;
		cluster = Hazelcast.getHazelcastInstanceByName(clusterName);
		
		GroupConfig gc = cluster.getConfig().getGroupConfig();
		Set<Member> memberSet = cluster.getCluster().getMembers();
		ClientConfig cc = new ClientConfig();
		cc.setGroupConfig(gc);
		for (Member member:memberSet)
			cc.addInetSocketAddress(member.getInetSocketAddress());
		
		
	}
	
	
		

	
	public RetryRemoteManagerImpl(HazelcastInstance clientInstance) {
		super(clientInstance);
		
		this.configManager = new RemoteConfigManager(clientInstance);
	}
	
	/**
	 * Add configurations from local config only if it doesn't exist on 
	 * the server
	 */
	private void addConfigurations() {
		
		Map<String,RetryConfiguration> configs = configManager.getConfigMapLocal();
		for (RetryConfiguration config:configs.values()) {
			if (configManager.getConfiguration(config.getType()) == null) {
				configManager.addConfiguration(config);
			} else {
				//TODO log something
			}
			
		}
	}
	
	@Override
	protected <T> RemoteRPC<T> rpcClass(String method,Object...signature) {
		
		return new RemoteManagerRPC<>(method, signature);
	}
	
	/**
	 * Event generated by server which is delegated to the local callback
	 * @param holder
	 * @return
	 * @throws Exception
	 */
	public boolean onCallback(RetryHolder holder) throws Exception {
		
		RetryCallback localCallback = localCallbackMap.get(holder.getType());
		
		if (localCallback == null) {
			throw new NoCallbackException();
		}
		try {
			return localCallback.onEvent(holder);
		}catch (Exception e) {
			//TODO: we don't want to throw back an except to the server
			//that it can't handle.
		}
		return false;
	}

	@Override
	public void addRetry(RetryHolder retry) throws NoCallbackException,
			ConfigException {
		HzSerializableRetryHolder holder = new HzSerializableRetryHolder(retry, new KryoSerializer());
		holder.setDeferPayloadSerialization(true);
		submitRPC("addRetry", holder);
	
	}

	@Override
	public void archiveRetry(RetryHolder retry) throws NoCallbackException,
			ConfigException {
		submitRPC("archiveRetry", retry);
		
	}

	@Override
	public void putRetry(List<RetryHolder> retryList)
			throws NoCallbackException, ConfigException {
		submitRPC("putRetry", retryList);
		
	}

	@Override
	public List<RetryHolder> getRetry(String retryId, String type) {
		List<RetryHolder> list =  submitRPC("getRetry", retryId,type);
		
		if (list instanceof HzSerializableRetryHolder ) {
			for (RetryHolder holder:list) {
				if (holder.getPayload() != null) {
					holder.setRetryData(new KryoSerializer().serializeToObject(holder.getPayload()) );
				}
			}
		}
		
		return list;
	}

	@Override
	public List<RetryHolder> getRetry(String retryId, String type,
			String secondaryIndex) {
		
		return submitRPC("getRetry", retryId,type,secondaryIndex);
		
	}

	@Override
	public void removeRetry(String retryId, String type) {
		
		submitRPC("getRetry", retryId,type);
		
	}

	@Override
	public int count(String type) {
		
		return submitRPC("count", type);
	}

	@Override
	public boolean exists(String retryId, String type) {
		return submitRPC("exists", retryId, type);
	}

	@Override
	public void registerCallback(RetryCallback callback, String type) {
		
		//ensure we have a proper static handle to this class:
		//TODO: should we expose this id handle in remote xml config?
		Retry.registerInst("client-handle",this);
		//TODO come up with client config of this 
		RemoteCallback remoteCallback = new DefaultRemoteCallback(this.configManager, type,"client-handle");
		submitToAll("registerRemoteCallback", remoteCallback);
		
		localCallbackMap.put(type, callback);
	}

	@Override
	public RetryCallback registeredCallback(String type) {
	
		return localCallbackMap.get(type);
	}

	@Override
	public void removeCallback(RetryCallback callback, String type) {
		throw new UnsupportedOperationException("");
		
	}

	@Override
	public RetryState getState(String type) {
		return submitRPC("getState", type);
	}

	@Override
	public Map<String, RetryState> getAllStates() {
		return submitRPC("getAllStates");
	}

	@Override
	public void registerTransitionListener(
			RetryTransitionListener transitionListener) {
		throw new UnsupportedOperationException("");
		
	}

	@Override
	public void removeTransitionListener(
			RetryTransitionListener transitionListener) {
		throw new UnsupportedOperationException("");
		
	}

	@Override
	public void shutdown() {
		hzClient.getLifecycleService().shutdown();
		
	}

	@Override
	public RetryConfigManager getConfigManager() {
		return configManager;
	}

	@Override
	public int countBySecondaryIndex(String type, String secondaryIndex) {
		return submitRPC("countBySecondaryIndex",type,secondaryIndex);
	}

	@Override
	public Collection<RetryHolder> bySecondaryIndex(String type,
			String secondaryIndex) {
		return submitRPC("bySecondaryIndex",type,secondaryIndex);
	}


	@Override
	public String getId() {
		return hzClient.getName();
	}

}
